name: Publish to Pypi
on:
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - main
      - '[0-9]+.[0-9]+.[0-9]+'  # Match M.m.hf pattern (e.g., 1.2.3, 2.0.1, etc.)

jobs:
  testpypipublish:
    name: Build and Publish Test Distribution
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request' &&
      github.event.pull_request.head.repo.full_name == github.repository &&
      (github.base_ref == 'main' || contains(github.base_ref, '.'))
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build
      run: |
        python setup.py sdist bdist_wheel
        twine check dist/*
      env:
        DEVBUILD: 1
    - name: Publish distribution package to Test PyPI
      if: |
        github.event.pull_request.head.repo.full_name == github.repository && 
        github.event_name == 'pull_request' &&
        (github.base_ref == 'main' || contains(github.base_ref, '.'))
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPITEST_PASSWORD }}
        repository-url: https://test.pypi.org/legacy/
  pypipublish:
    name: Build and Publish Production Distribution
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build
      run: |
        python setup.py sdist bdist_wheel
        twine check dist/*
    - name: Publish distribution package to PyPI
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_PASSWORD }}
